### ISSUE TITLE
Source is not converted to ES5.

### ISSUE THREAD

**Issue by gimdongwoo** [vladm3/alloy.babel#2]
src/controllers/index.js
```
const a = 'test';

var doClick = (e) => {
  alert($.label.text + a);
}

$.index.open();
```

This is transcoded result.

app/controllers/index.js

```
const a = 'test';

var doClick = e => {
  alert($.label.text + a);
};

$.index.open();
```

Error when compiling with Alloy 1.19.11

<img width="977" alt="2017-06-16 2 06 30" src="https://user-images.githubusercontent.com/7310854/27193186-efe15e0c-5238-11e7-9906-c18afdc63783.png">

I think it should be completely transcoded to ES5.

Maybe `babel-preset-es2015` should be added.

**Comment by vladm3** [comment]
@gimdongwoo Thanks for your PR. It's implied that the user does Babel configuration using .babelrc file by themselves.
Also this project is not maintained anymore. I created a new, better stack of plugins for transforming Titanium code (https://github.com/vladm3/ti.transform).
Closing the issue and PR.
